server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_managementProductRestApi?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    ma.formation.webService.rest: DEBUG
